apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cmpt756pj-item
  labels:
    app: cmpt756pj-item
    release: c756
spec:
  namespaceSelector:
    matchNames:
    - c756ns
  selector:
    matchLabels:
      app: cmpt756pj-item
  endpoints:
  - port: http
    path: /metrics
