apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cmpt756pj-user
  labels:
    app: cmpt756pj-user
    release: c756
spec:
  namespaceSelector:
    matchNames:
      - c756ns
  selector:
    matchLabels:
      app: cmpt756pj-user
  endpoints:
    - port: http
      path: /metrics
